## ---------- ##
## Containers ##
## ---------- ##
sisana_container: "docker://rtpop/sisana_container:latest"

## Number of cores ##
ncores: 30

## ----------- ##
## Directories ##
## ----------- ## 

src_dir: "src" # Code directory
data_dir: "data"
output_dir: "output"

## ----------- ##
## Input files ##
## ----------- ##

# these files should be placed in the data directory
exp_file: "matched_exp_final.txt" # should be text file with genes in rows and samples in columns
motif_prior_file: "motif_prior.tsv"
ppi_prior_file: "ppi_prior_2024.tsv"
sample_anno: "samples_annotation.csv"
gene_anno: "GENCODEv36-gene-annotation.txt"

## ----------------- ##
## SISANA parameters ##
## ----------------- ##

# this file will be generated automatically by src/generate_sisana_config.py
# specify the file name and the desired parameters below
sisana_config: "sisana_params.yml"
sisana_method: "lioness" # panda or lioness
min_exp_samples: 5 # the minimum number of samples in which a gene should be expressed to be kept
output_format: "text" # npy or "text"; Note that text output will be very large for lioness networks
